{"id":7,"summary":"Deep stubbing with generic responses in the call chain is not working","description": "Deep stubbing will throw an Exception if multiple generics occur in the call chain. For instance, consider having a mock myMock1 that provides a function that returns a generic T. If T also has a function that returns a generic, an Exception with the message \"Raw extraction not supported for : 'null'\" will be thrown. I think, the issue is that further generics are not possible to be mocked by ReturnsDeepStubsSerializationFallback since the GenericMetadataSupport is \"closed\" at this point."}